using UnityEngine;
using UnityEngine.UI;
using TMPro;
using System.Collections.Generic;

public class LastCardDisplay : MonoBehaviour
{
    [Header("Ссылки")]
    [SerializeField] private RawImage cardDisplay; 
    [SerializeField] private TMP_Text cardNameText; // Английское название
    [SerializeField] private TMP_Text cardNameText2; // Русское название

    // Словарь для перевода
    private Dictionary<string, string> _translationDictionary = new Dictionary<string, string>()
    {
        {"abdomen", "живот, брюхо"},
        {"add", "добавлять, прибавлять"},
        {"adult", "взрослый"},
        {"segment", "часть, отрезок"},
        {"annulus", "кольцо"},
        {"aqua", "вода, цвет морской волны"},
        {"aquamarine", "аквамариновый"},
        {"arch", "арка"},
        {"arm", "рука"},
        {"armchair", "кабинетное кресло"},
        {"arrow", "стрела"},
        {"artificial", "искусственный, ненастоящий"},
        {"attic", "чердак"},
        {"aunt", "тётя, тетушка"},
        {"baby", "ребёнок"},
        {"back", "спина"},
        {"balcony", "балкон, лоджия"},
        {"barbecue", "шашлык, гриль"},
        {"basement", "подвал"},
        {"bathroom", "ванная, ванная комната"},
        {"battery", "батарея, аккумулятор"},
        {"be angry", "злиться, разозлиться"},
        {"bear", "медведь"},
        {"beat", "бить"},
        {"bedroom", "спальная комната"},
        {"bee", "пчела"},
        {"bench", "скамейка"},
        {"big", "большой"},
        {"billiard room", "бильярдная"},
        {"bite", "укусить"},
        {"black and white", "черно-белый"},
        {"black", "черный"},
        {"blow", "дуть, веять"},
        {"blue", "синий"},
        {"boar", "кабан"},
        {"bolt", "болт"},
        {"bone", "кость"},
        {"bookcase", "книжный шкаф"},
        {"bottom", "низ"},
        {"boy", "мальчик"},
        {"brick", "кирпич"},
        {"bride", "невеста"},
        {"bring up", "поднимать"},
        {"brother", "брат"},
        {"brown", "коричневый"},
        {"build", "строить"},
        {"building", "строительство"},
        {"cabinet", "шкаф"},
        {"cage", "клетка"},
        {"call", "звонок"},
        {"care", "забота"},
        {"carry", "переноска"},
        {"cat", "кошка"},
        {"catch", "ловить, поймать"},
        {"chase", "охотиться, преследовать"},
        {"chest", "сундук"},
        {"children", "дети"},
        {"chimney", "дымоход"},
        {"circle", "круг"},
        {"clap", "хлопать"},
        {"clean", "чистить, убирать"},
        {"climb", "взбираться, лезть"},
        {"closed", "закрытый"},
        {"closet", "шкаф"},
        {"coffee", "кофе"},
        {"cold", "холодный"},
        {"color", "цветной"},
        {"column", "колонна"},
        {"comb", "расчёска, гребень"},
        {"cone", "конус"},
        {"confuse", "запутывать, смущать"},
        {"cook", "готовить"},
        {"couch", "диван"},
        {"couple", "супружеская пара"},
        {"cow", "корова"},
        {"crawl", "ползать"},
        {"crescent", "полукруг, полумесяц"},
        {"crocodile", "крокодил"},
        {"cross", "крест"},
        {"cry", "плакать"},
        {"cube", "куб"},
        {"cupboard", "шкаф"},
        {"curly", "кудрявый"},
        {"curve", "кривая"},
        {"cylinder", "цилиндр"},
        {"dance", "танец"},
        {"dark", "темнота"},
        {"daughter", "дочь"},
        {"decagon", "десятиугольник"},
        {"deer", "олень"},
        {"descend", "спускаться"},
        {"desk", "письменный стол"},
        {"dig", "копать, рыть"},
        {"dining room", "столовая"},
        {"dirty", "грязный, нечистый"},
        {"dive", "нырять"},
        {"dodecagon", "двенадцатиугольник"},
        {"dog", "собака"},
        {"donkey", "осел"},
        {"door chain", "дверная цепь"},
        {"door", "дверь"},
        {"doormat", "половик, дверной коврик"},
        {"dream", "мечта"},
        {"dressed", "одетый"},
        {"drink", "пить"},
        {"drive", "ехать"},
        {"dry", "сухой, высохший"},
        {"dull", "тупой"},
        {"eat", "есть"},
        {"edible", "съедобный"},
        {"elbow", "локоть"},
        {"elderly", "пожилой"},
        {"elephant", "слон"},
        {"elevator", "лифт"},
        {"ellipsoid", "эллипсоид"},
        {"empty", "пустой"},
        {"fall", "падать"},
        {"family", "семья"},
        {"fast", "быстрый, скоростной"},
        {"fat", "толстый"},
        {"father", "отец"},
        {"fear", "Испугаться, пугать"},
        {"feed", "кормить"},
        {"fence", "забор"},
        {"finger", "палец"},
        {"fireplace", "камин"},
        {"fish", "рыба"},
        {"fist", "кулак"},
        {"fix", "исправлять"},
        {"flat", "плоский"},
        {"flowerbed", "клумба"},
        {"fly", "муха"},
        {"foot", "нога"},
        {"Forest animals", "лесные животные"},
        {"fountain", "фонтан"},
        {"fox", "лиса"},
        {"foyer", "прихожая, холл"},
        {"fragile", "хрупкий"},
        {"frustum", "усеченный конус"},
        {"full", "целый, полный"},
        {"furniture", "мебель"},
        {"garage", "гараж"},
        {"garden", "сад"},
        {"gate", "ворота"},
        {"gazebo", "беседка"},
        {"gear", "оборудование"},
        {"giraffe", "жираф"},
        {"girl", "девочка"},
        {"give", "дать, выдавать"},
        {"go", "идти"},
        {"goat", "коза"},
        {"grandchildren", "внуки"},
        {"granddaughter", "внучка"},
        {"grandfather", "дедушка"},
        {"grandparents", "дедушка и бабушка"},
        {"grandson", "внук"},
        {"grangmother", "бабушка"},
        {"gray", "серый"},
        {"green", "зелёный"},
        {"greenhouse", "теплица"},
        {"grimace", "гримаса"},
        {"groom", "жених"},
        {"guinea pig", "морская свинка"},
        {"gutter", "водосток"},
        {"hall corridor", "коридор"},
        {"hammock", "гамак"},
        {"hamster", "хомяк"},
        {"hand", "рука"},
        {"hang", "вешать"},
        {"hanger", "вешалка"},
        {"hanging basket", "подвесная корзина"},
        {"happy", "счастливый"},
        {"hare", "заяц"},
        {"has", "иметь, обладать"},
        {"head", "голова"},
        {"hear", "слышать"},
        {"heart", "сердце"},
        {"heavy", "тяжелый"},
        {"hedge", "изгородь"},
        {"hedgehog", "еж"},
        {"heptagon", "семиугольник"},
        {"hexagon", "шестиугольник"},
        {"hide", "спрятаться"},
        {"high", "высокий, высокое"},
        {"hip", "бедро"},
        {"hippopotamus", "бегемот"},
        {"hold", "держать"},
        {"horse", "лошадь"},
        {"hot", "горячий"},
        {"house", "дом"},
        {"hug", "обнимать"},
        {"husband", "муж"},
        {"intercom", "домофон"},
        {"iron", "железо"},
        {"ivory", "слоновая кость"},
        {"jaguar", "ягуар"},
        {"jump", "прыжок"},
        {"key", "ключ"},
        {"khaki", "хаки"},
        {"kick", "удар"},
        {"kind", "добрый"},
        {"kiss", "поцелуй"},
        {"kitchen", "кухня"},
        {"kite", "воздушный змей"},
        {"knee", "колено"},
        {"knock", "стук"},
        {"lady", "леди"},
        {"lama", "лама"},
        {"laugh", "смеяться"},
        {"launch", "запуск"},
        {"laundry basket", "корзина для белья"},
        {"lawn", "газон"},
        {"lay", "лежать"},
        {"left", "левая"},
        {"leg", "нога"},
        {"lens", "объектив"},
        {"library", "библиотека"},
        {"light coloured", "светлый цветной"},
        {"light", "свет"},
        {"lion", "лев"},
        {"living room", "гостиная"},
        {"lock", "замок"},
        {"long", "длинный"},
        {"look into", "заглянуть"},
        {"look", "смотреть"},
        {"low", "низкий"},
        {"lynx", "рысь"},
        {"mailbox", "почтовый ящик"},
        {"man", "человек"},
        {"many", "много"},
        {"maroon", "бордовый"},
        {"mole", "крот"},
        {"monkey", "обезьяна"},
        {"moose", "лось"},
        {"mother", "мать"},
        {"mouse", "мышь"},
        {"mow", "косить"},
        {"muskox", "мускокс"},
        {"nape", "затылок"},
        {"neck", "шея"},
        {"nephew", "племянник"},
        {"new", "новый"},
        {"newborn", "новорожденный"},
        {"niece", "племянница"},
        {"nonagon", "девятиугольник"},
        {"octagon", "восьмиугольник"},
        {"octahedron", "восьмигранник"},
        {"office den", "офисное помещение"},
        {"old man", "старик"},
        {"old woman", "старуха"},
        {"old", "старый"},
        {"olive", "олива"},
        {"open", "открыть"},
        {"Opposites", "Противоположности"},
        {"orange", "оранжевый"},
        {"oval", "овал"},
        {"paint", "краска"},
        {"palm", "пальма"},
        {"panda", "панда"},
        {"parallelepiped", "параллелепипед"},
        {"parallelogram", "параллелограмм"},
        {"parents", "родители"},
        {"parking", "парковка"},
        {"parrot", "попугай"},
        {"path", "путь"},
        {"pee", "писать"},
        {"peep out", "подглядывать"},
        {"penguin", "пингвин"},
        {"pentagon", "пентагон"},
        {"pig", "свинья"},
        {"pink", "розовый"},
        {"play", "играть"},
        {"playroom", "игровая комната"},
        {"poisonous", "ядовитый"},
        {"polygon", "полигон"},
        {"pond", "пруд"},
        {"pony", "пони"},
        {"pool", "бассейн"},
        {"poop", "какашка"},
        {"poor", "бедный"},
        {"porch swing", "качели на крыльце"},
        {"porch", "крыльцо"},
        {"pouf", "пуф"},
        {"pour over", "переливать"},
        {"pray", "молиться"},
        {"pregnant", "беременная"},
        {"present", "подарок"},
        {"press", "пресса"},
        {"prickly", "колючий"},
        {"pull", "тянуть"},
        {"purple", "фиолетовый"},
        {"push", "нажать"},
        {"put", "поставить"},
        {"quadrilateral", "четырехугольник"},
        {"rabbit", "кролик"},
        {"raccoon", "енот"},
        {"ram", "баран"},
        {"real", "настоящий"},
        {"rectangle", "прямоугольник"},
        {"red", "красный"},
        {"reindeer", "северный олень"},
        {"relax", "расслабиться"},
        {"rhinoceros", "носорог"},
        {"rhombus", "ромб"},
        {"rich", "богатый"},
        {"ride", "ехать"},
        {"right", "правильно"},
        {"ripe", "спелый"},
        {"rocking chair", "кресло-качалка"},
        {"roll", "качаться"},
        {"roof", "крыша"},
        {"rooms", "комнаты"},
        {"rotten", "гнилой"},
        {"row", "ряд"},
        {"run", "бежать"},
        {"sad", "грустный"},
        {"safe", "безопасный"},
        {"sauna", "сауна"},
        {"saw", "пила"},
        {"scratch", "царапина"},
        {"seal", "печать"},
        {"sector", "сектор"},
        {"see", "см."},
        {"semicircle", "полукруг"},
        {"sharp", "острый"},
        {"shave", "бриться"},
        {"shed", "сарай"},
        {"sheep", "овца"},
        {"shoe cabinet", "тумба для обуви"},
        {"shoot", "стрелять"},
        {"short", "короткий"},
        {"shoulder", "плечо"},
        {"shout", "кричать"},
        {"show", "показать"},
        {"simple", "простой"},
        {"sing", "петь"},
        {"sister", "сестра"},
        {"sit", "сидеть"},
        {"skeleton", "скелет"},
        {"skull", "череп"},
        {"skunk", "скунс"},
        {"sleep", "спать"},
        {"slim", "стройный"},
        {"slow", "медленный"},
        {"small", "маленький"},
        {"smoke", "дым"},
        {"smooth", "гладкий"},
        {"sneeze", "чихнуть"},
        {"sniff", "нюхать"},
        {"sofa", "диван"},
        {"soft", "мягкий"},
        {"son", "сын"},
        {"sour", "кислый"},
        {"sphere", "сфера"},
        {"splash", "брызги"},
        {"square pyramid", "квадратная пирамида"},
        {"square", "квадрат"},
        {"squeeze", "сжимать"},
        {"squirrel", "белка"},
        {"staircase", "лестница"},
        {"stand", "стойка"},
        {"star", "звезда"},
        {"stool", "табурет"},
        {"straight hair", "прямые волосы"},
        {"straight", "прямой"},
        {"strong", "сильный"},
        {"sun lounger", "шезлонг"},
        {"sunbathe", "загорать"},
        {"sweep", "подметать"},
        {"sweet", "сладкий"},
        {"swim", "плавать"},
        {"swimming pool", "бассейн"},
        {"swing", "качели"},
        {"swivel chair", "вращающийся стул"},
        {"table", "стол"},
        {"take a shower", "принять душ"},
        {"teal", "тиль"},
        {"teenager", "подросток"},
        {"thick", "толстый"},
        {"thin", "тонкий"},
        {"think", "думать"},
        {"throw up", "вырвать"},
        {"throw", "бросить"},
        {"tiger", "тигр"},
        {"tough", "жесткий"},
        {"trapezoid", "трапеция"},
        {"triangle", "треугольник"},
        {"turtle", "черепаха"},
        {"tv stand", "телевизионная подставка"},
        {"twins", "близнецы"},
        {"uncle", "дядя"},
        {"unclothed", "без одежды"},
        {"upper", "верхняя часть"},
        {"vacuum", "вакуум"},
        {"veranda", "веранда"},
        {"volume", "объем"},
        {"wake up", "просыпаться"},
        {"walk", "прогулка"},
        {"wall shelf", "настенная полка"},
        {"wall", "стена"},
        {"walrus", "морж"},
        {"wardrobe", "гардероб"},
        {"wash", "мыть"},
        {"watch TV", "смотреть телевизор"},
        {"water", "вода"},
        {"wet", "мокрый"},
        {"whale", "кит"},
        {"whisper", "шепот"},
        {"white", "белый"},
        {"wicked", "злой"},
        {"wife", "жена"},
        {"window", "окно"},
        {"wolf", "волк"},
        {"woman", "женщина"},
        {"work", "работа"},
        {"wrist", "запястье"},
        {"yawn", "зевать"},
        {"yellow", "желтый"},
        {"young", "молодой"},
        {"youth", "молодежь"},
        {"zebra", "зебра"},

    };

    private Texture2D _lastTexture;
    private string _lastTextureName;

    public void UpdateLastCard(Texture2D texture)
    {
        if (texture == null) return;

        _lastTexture = texture;
        _lastTextureName = texture.name;

        // Обновляем UI
        cardDisplay.texture = _lastTexture;
        string cleanName = CleanUpName(_lastTextureName);
        cardNameText.text = cleanName;
        
        // Пытаемся получить перевод
        if(_translationDictionary.TryGetValue(cleanName.ToLower(), out string russianName))
        {
            cardNameText2.text = russianName;
        }
        else
        {
            cardNameText2.text = "Нет перевода"; 
        }
    }

    private string CleanUpName(string originalName)
    {
        return System.IO.Path.GetFileNameWithoutExtension(originalName);
    }
}